#======================
#       Favicon        
#======================
favicon: /images/favicon.ico


#======================
#       Menu        
#======================
menu:
  home: /
  archives: /archives
  # portfolio: /portfolio
  # about: /about
  # categories: /categories
  # tags: /tags


#======================
#       Personal        
#======================
show_tag: true
show_category: false


#======================
#     Read More     
#======================
excerpt_link: Read More


#======================
#      Fancybox     
#======================
fancybox: true


#======================
#      Comment    
#======================
disqus_shortname:


#======================
#      Social    
#======================
social: 
  email: 
  instagram: 
  douban: 
  linkedin: 
  weibo: 
  stackoverflow: 
  facebook: 
  twitter: 
  github: 
  rss: 
  google: 
  zhihu: 
  pocket: 


#======================
#   Google Analytics    
#======================
google_analytics: 


#======================
#      Portfolio        
#======================
portfolio:
  subtitle: Some Works

#======================
#      About        
#======================
about:
  avatar: 
  subtitle: About Me




#=============================================================================
#               !!! TO-DO !!! Please Don't fill down below
#=============================================================================


#======================
#    Search(TO-DO)    
#======================
# local_search: false
## Add below to ../../_config.yml
# search: 
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000


#======================
#   Copyright(TO-DO)   
#======================
## https://creativecommons.org/ 
# copyright: 


#======================
#   LeanCloud(TO-DO)    
#======================
# leancloud:
#   app_id: 
#   app_key: 


#======================
#   Mathjax(TO-DO)
#======================
# mathjax: false